message.template.create_content_in_joined_group:
  expected_config: { }
  update_actions:
    change:
      third_party_settings:
        activity_logger:
          activity_entity_condition: group_content_node_single_group
